name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # ou 'master', dependendo do seu branch padrão

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload dos arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'root'

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v4
